interface CollageImageBase {
  id: string;
  src: string;
  alt: string;
  top: number;
  width: number;
  rotation: number;
  zIndex: number;
}

interface LeftAnchoredImage extends CollageImageBase {
  anchor: 'left';
  left: number;
}

interface RightAnchoredImage extends CollageImageBase {
  anchor: 'right';
  right: number;
}

export type CollageImageData = LeftAnchoredImage | RightAnchoredImage;

// All position and size values are in px (fixed, no scaling).
// Left-anchored images: pinned to left edge via `left`.
// Right-anchored images: pinned to right edge via `right`.
// Viewport width changes only affect the center gap between clusters.

export const collageImages: CollageImageData[] = [
  {
    id: 'tiger-stamp',
    src: '/images/collage/tiger-stamp.png',
    alt: 'Vintage tiger postage stamp',
    anchor: 'left',
    left: 25,
    top: 17,
    width: 98,
    rotation: 0,
    zIndex: 10,
  },
  {
    id: 'blue-dragon',
    src: '/images/collage/blue-dragon.png',
    alt: 'Blue dragon paper cutout illustration',
    anchor: 'left',
    left: -3,
    top: 16,
    width: 268,
    rotation: 42,
    zIndex: 5,
  },
  {
    id: 'disco-ball',
    src: '/images/collage/disco-ball.png',
    alt: 'Disco ball hanging from chain',
    anchor: 'left',
    left: 276,
    top: -216,
    width: 188,
    rotation: 0,
    zIndex: 7,
  },
  {
    id: 'concert-ticket',
    src: '/images/collage/concert-ticket.png',
    alt: 'Vintage concert ticket stub',
    anchor: 'right',
    right: 104,
    top: 418,
    width: 138,
    rotation: 4,
    zIndex: 6,
  },
  {
    id: 'gold-frame-bunny',
    src: '/images/collage/gold-frame-bunny.png',
    alt: 'Pink bunny painting in ornate gold frame',
    anchor: 'right',
    right: 131,
    top: 37,
    width: 241,
    rotation: 3,
    zIndex: 10,
  },
  {
    id: 'coffee-ring',
    src: '/images/collage/coffee-ring.png',
    alt: 'Coffee cup ring stain',
    anchor: 'right',
    right: -68,
    top: -80,
    width: 255,
    rotation: 0,
    zIndex: 0,
  },
  {
    id: 'sun-face',
    src: '/images/collage/sun-face.png',
    alt: 'Vintage engraved sun with face',
    anchor: 'right',
    right: 1,
    top: 211,
    width: 208,
    rotation: 0,
    zIndex: 7,
  },
  {
    id: 'bookshelf',
    src: '/images/collage/bookshelf.png',
    alt: 'Antique bookshelf with leather-bound books',
    anchor: 'left',
    left: -220,
    top: 348,
    width: 478,
    rotation: 0,
    zIndex: 2,
  },
  {
    id: 'earring-back',
    src: '/images/collage/earring.png',
    alt: 'Ornate silver jhumka earring',
    anchor: 'right',
    right: 277,
    top: 624,
    width: 37,
    rotation: -11,
    zIndex: 9,
  },
  {
    id: 'earring-front',
    src: '/images/collage/earring.png',
    alt: 'Ornate silver jhumka earring',
    anchor: 'right',
    right: 292,
    top: 626,
    width: 34,
    rotation: 11,
    zIndex: 8,
  },
  {
    id: 'f1-car',
    src: '/images/collage/f1-car.png',
    alt: 'Vintage red Formula 1 race car illustration',
    anchor: 'left',
    left: 83,
    top: 587,
    width: 375,
    rotation: -2,
    zIndex: 12,
  },
  {
    id: 'card-spades',
    src: '/images/collage/playing-card-spades.png',
    alt: 'Vintage 10 of spades playing card',
    anchor: 'left',
    left: 97,
    top: 280,
    width: 80,
    rotation: -21,
    zIndex: 1,
  },
  {
    id: 'card-queen',
    src: '/images/collage/playing-card-queen.png',
    alt: 'Vintage Queen of Hearts playing card',
    anchor: 'left',
    left: 128,
    top: 281,
    width: 90,
    rotation: 2,
    zIndex: 1,
  },
  {
    id: 'cd-disc',
    src: '/images/collage/cd-disc.png',
    alt: 'CD with Summer nights with friends written on it',
    anchor: 'right',
    right: 3,
    top: 85,
    width: 177,
    rotation: -5,
    zIndex: 9,
  },
  {
    id: 'letter-T-1',
    src: '/images/collage/letter-T.png',
    alt: 'letter T 1',
    anchor: 'right',
    right: 264,
    top: 605,
    width: 43,
    rotation: 5,
    zIndex: 8,
  },
  {
    id: 'letter-H-1',
    src: '/images/collage/letter-H.png',
    alt: 'letter H 1',
    anchor: 'right',
    right: 220,
    top: 604,
    width: 43,
    rotation: -4,
    zIndex: 8,
  },
  {
    id: 'letter-A',
    src: '/images/collage/letter-A.png',
    alt: 'letter A',
    anchor: 'right',
    right: 165,
    top: 601,
    width: 43,
    rotation: -1,
    zIndex: 8,
  },
  {
    id: 'letter-T-2',
    src: '/images/collage/letter-T.png',
    alt: 'letter T 2',
    anchor: 'right',
    right: 121,
    top: 601,
    width: 43,
    rotation: 3,
    zIndex: 8,
  },
  {
    id: 'letter-S',
    src: '/images/collage/letter-S.png',
    alt: 'letter S',
    anchor: 'right',
    right: 64,
    top: 599,
    width: 43,
    rotation: -6,
    zIndex: 11,
  },
  {
    id: 'letter-H-2',
    src: '/images/collage/letter-H.png',
    alt: 'letter H 2',
    anchor: 'right',
    right: 105,
    top: 651,
    width: 43,
    rotation: 1,
    zIndex: 8,
  },
  {
    id: 'letter-O',
    src: '/images/collage/letter-O.png',
    alt: 'letter O',
    anchor: 'right',
    right: 55,
    top: 651,
    width: 43,
    rotation: -3,
    zIndex: 8,
  },
  {
    id: 'letter-T-3',
    src: '/images/collage/letter-T.png',
    alt: 'letter T 3',
    anchor: 'right',
    right: 5,
    top: 656,
    width: 43,
    rotation: 5,
    zIndex: 8,
  },
  {
    id: 'peony-back',
    src: '/images/collage/peony.png',
    alt: 'Pink peony flower with green leaves',
    anchor: 'right',
    right: 21,
    top: 624,
    width: 130,
    rotation: 25,
    zIndex: 6,
  },
  {
    id: 'peony-front',
    src: '/images/collage/peony.png',
    alt: 'Pink peony flower with green leaves',
    anchor: 'right',
    right: 91,
    top: 601,
    width: 168,
    rotation: -12,
    zIndex: 5,
  },
];
