export interface CollageImageData {
  id: string;
  src: string;
  alt: string;
  position: { x: number; y: number };
  size: number;
  rotation: number;
  zIndex: number;
  bleed?: 'top' | 'bottom' | 'left' | 'right' | 'bottom-right';
}

export const collageImages: CollageImageData[] = [
  {
    id: 'tiger-stamp',
    src: 'tiger-stamp.png',
    alt: 'Vintage tiger postage stamp',
    position: { x: 1.6, y: 2.5 },
    size: 5.7,
    rotation: 0,
    zIndex: 10,
  },
  {
    id: 'blue-dragon',
    src: 'blue-dragon.png',
    alt: 'Blue dragon paper cutout illustration',
    position: { x: -1, y: 5 },
    size: 15,
    rotation: 48,
    zIndex: 5,
    bleed: 'left',
  },
  {
    id: 'disco-ball',
    src: 'disco-ball.png',
    alt: 'Disco ball hanging from chain',
    position: { x: 13.7, y: -11.4 },
    size: 9,
    rotation: 0,
    zIndex: 7,
    bleed: 'top',
  },
  {
    id: 'concert-ticket',
    src: 'concert-ticket.png',
    alt: 'Vintage concert ticket stub',
    position: { x: 11.9, y: 25.3 },
    size: 7,
    rotation: 10,
    zIndex: 6,
  },
  {
    id: 'gold-frame-bunny',
    src: 'gold-frame-bunny.png',
    alt: 'Pink bunny painting in ornate gold frame',
    position: { x: 58.1, y: 3.4 },
    size: 14,
    rotation: 3,
    zIndex: 11,
  },
  {
    id: 'coffee-ring',
    src: 'coffee-ring.png',
    alt: 'Coffee cup ring stain',
    position: { x: 69.3, y: -7.2 },
    size: 14.9,
    rotation: 0,
    zIndex: 9,
  },
  {
    id: 'sun-face',
    src: 'sun-face.png',
    alt: 'Vintage engraved sun with face',
    position: { x: 67.1, y: 22.7 },
    size: 12,
    rotation: 0,
    zIndex: 3,
    bleed: 'right',
  },
  {
    id: 'bookshelf',
    src: 'bookshelf.png',
    alt: 'Antique bookshelf with leather-bound books',
    position: { x: -19.1, y: 41.1 },
    size: 32.3,
    rotation: 0,
    zIndex: 2,
    bleed: 'left',
  },
  {
    id: 'earring-back',
    src: 'earring.png',
    alt: 'Ornate silver jhumka earring',
    position: { x: 11.3, y: 40.4 },
    size: 3.1,
    rotation: -10,
    zIndex: 7,
  },
  {
    id: 'earring-front',
    src: 'earring.png',
    alt: 'Ornate silver jhumka earring',
    position: { x: 12.6, y: 39.6 },
    size: 3,
    rotation: -30,
    zIndex: 8,
  },
  {
    id: 'f1-car',
    src: 'f1-car.png',
    alt: 'Vintage red Formula 1 race car illustration',
    position: { x: 4.7, y: 72.4 },
    size: 22.5,
    rotation: -2,
    zIndex: 6,
  },
  {
    id: 'card-spades',
    src: 'playing-card-spades.png',
    alt: 'Vintage 10 of spades playing card',
    position: { x: 65.3, y: 49.2 },
    size: 6.5,
    rotation: -14,
    zIndex: 5,
  },
  {
    id: 'card-queen',
    src: 'playing-card-queen.png',
    alt: 'Vintage Queen of Hearts playing card',
    position: { x: 67.1, y: 49.9 },
    size: 7,
    rotation: 7,
    zIndex: 6,
  },
  {
    id: 'cd-disc',
    src: 'cd-disc.png',
    alt: 'CD with Summer nights with friends written on it',
    position: { x: 59.9, y: 56.9 },
    size: 9,
    rotation: -8,
    zIndex: 1,
  },
  {
    id: 'letter-T-1',
    src: 'letter-T.png',
    alt: 'letter T 1',
    position: { x: 57.3, y: 77.3 },
    size: 2.2,
    rotation: 3,
    zIndex: 8,
  },
  {
    id: 'letter-H-1',
    src: 'letter-H.png',
    alt: 'letter H 1',
    position: { x: 59.4, y: 76.2 },
    size: 2.7,
    rotation: -9,
    zIndex: 8,
  },
  {
    id: 'letter-A',
    src: 'letter-A.png',
    alt: 'letter A',
    position: { x: 62.3, y: 76.5 },
    size: 2.2,
    rotation: 2,
    zIndex: 8,
  },
  {
    id: 'letter-T-2',
    src: 'letter-T.png',
    alt: 'letter T 2',
    position: { x: 64.5, y: 76.6 },
    size: 2.2,
    rotation: -6,
    zIndex: 8,
  },
  {
    id: 'letter-S',
    src: 'letter-S.png',
    alt: 'letter S',
    position: { x: 67.7, y: 76.9 },
    size: 2.2,
    rotation: 6,
    zIndex: 8,
  },
  {
    id: 'letter-H-2',
    src: 'letter-H.png',
    alt: 'letter H 2',
    position: { x: 59.7, y: 82 },
    size: 2.2,
    rotation: 1,
    zIndex: 8,
  },
  {
    id: 'letter-O',
    src: 'letter-O.png',
    alt: 'letter O',
    position: { x: 62.2, y: 81.8 },
    size: 1.7,
    rotation: -3,
    zIndex: 8,
  },
  {
    id: 'letter-T-3',
    src: 'letter-T.png',
    alt: 'letter T 3',
    position: { x: 63.9, y: 81.2 },
    size: 3.2,
    rotation: 12,
    zIndex: 8,
  },
  {
    id: 'peony-back',
    src: 'peony.png',
    alt: 'Pink peony flower with green leaves',
    position: { x: 66.5, y: 73.8 },
    size: 10,
    rotation: -11,
    zIndex: 3,
    bleed: 'bottom-right',
  },
  {
    id: 'peony-front',
    src: 'peony.png',
    alt: 'Pink peony flower with green leaves',
    position: { x: 71.9, y: 76.4 },
    size: 8.5,
    rotation: 34,
    zIndex: 5,
  },
];
