interface CollageImageBase {
  id: string;
  src: string;
  alt: string;
  top: number;
  width: number;
  rotation: number;
  zIndex: number;
}

interface LeftAnchoredImage extends CollageImageBase {
  anchor: 'left';
  left: number;
}

interface RightAnchoredImage extends CollageImageBase {
  anchor: 'right';
  right: number;
}

export type CollageImageData = LeftAnchoredImage | RightAnchoredImage;

// All position and size values are in px (fixed, no scaling).
// Left-anchored images: pinned to left edge via `left`.
// Right-anchored images: pinned to right edge via `right`.
// Viewport width changes only affect the center gap between clusters.

export const collageImages: CollageImageData[] = [
  // ── Left cluster ──
  {
    id: 'tiger-stamp',
    src: '/images/collage/tiger-stamp.png',
    alt: 'Vintage tiger postage stamp',
    anchor: 'left',
    left: 23,
    top: 21,
    width: 77,
    rotation: 0,
    zIndex: 10,
  },
  {
    id: 'blue-dragon',
    src: '/images/collage/blue-dragon.png',
    alt: 'Blue dragon paper cutout illustration',
    anchor: 'left',
    left: -22,
    top: 56,
    width: 205,
    rotation: 50,
    zIndex: 5,
  },
  {
    id: 'disco-ball',
    src: '/images/collage/disco-ball.png',
    alt: 'Disco ball hanging from chain',
    anchor: 'left',
    left: 204,
    top: -71,
    width: 119,
    rotation: 0,
    zIndex: 11,
  },
  {
    id: 'concert-ticket',
    src: '/images/collage/concert-ticket.png',
    alt: 'Vintage concert ticket stub',
    anchor: 'left',
    left: 173,
    top: 201,
    width: 101,
    rotation: 11,
    zIndex: 6,
  },
  {
    id: 'bookshelf',
    src: '/images/collage/bookshelf.png',
    alt: 'Antique bookshelf with leather-bound books',
    anchor: 'left',
    left: -281,
    top: 334,
    width: 465,
    rotation: 0,
    zIndex: 7,
  },
  {
    id: 'earring-back',
    src: '/images/collage/earring.png',
    alt: 'Ornate silver jhumka earring',
    anchor: 'left',
    left: 158,
    top: 332,
    width: 35,
    rotation: 3,
    zIndex: 8,
  },
  {
    id: 'earring-front',
    src: '/images/collage/earring.png',
    alt: 'Ornate silver jhumka earring',
    anchor: 'left',
    left: 176,
    top: 331,
    width: 35,
    rotation: -19,
    zIndex: 9,
  },
  {
    id: 'f1-car',
    src: '/images/collage/f1-car.png',
    alt: 'Vintage red Formula 1 race car illustration',
    anchor: 'left',
    left: 47,
    top: 607,
    width: 307,
    rotation: -2,
    zIndex: 20,
  },
  // ── Right cluster ──
  {
    id: 'gold-frame-bunny',
    src: '/images/collage/gold-frame-bunny.png',
    alt: 'Pink bunny painting in ornate gold frame',
    anchor: 'right',
    right: 108,
    top: 39,
    width: 190,
    rotation: 3,
    zIndex: 11,
  },
  {
    id: 'coffee-ring',
    src: '/images/collage/coffee-ring.png',
    alt: 'Coffee cup ring stain',
    anchor: 'right',
    right: -54,
    top: -72,
    width: 206,
    rotation: 2,
    zIndex: 9,
  },
  {
    id: 'sun-face',
    src: '/images/collage/sun-face.png',
    alt: 'Vintage engraved sun with face',
    anchor: 'right',
    right: 0,
    top: 173,
    width: 180,
    rotation: 0,
    zIndex: 3,
  },
  {
    id: 'card-spades',
    src: '/images/collage/playing-card-spades.png',
    alt: 'Vintage 10 of spades playing card',
    anchor: 'right',
    right: 115,
    top: 397,
    width: 90,
    rotation: -20,
    zIndex: 5,
  },
  {
    id: 'card-queen',
    src: '/images/collage/playing-card-queen.png',
    alt: 'Vintage Queen of Hearts playing card',
    anchor: 'right',
    right: 79,
    top: 397,
    width: 100,
    rotation: 4,
    zIndex: 6,
  },
  {
    id: 'cd-disc',
    src: '/images/collage/cd-disc.png',
    alt: 'CD with Summer nights with friends written on it',
    anchor: 'right',
    right: 166,
    top: 450,
    width: 100,
    rotation: -5,
    zIndex: 4,
  },
  // ── "THAT'S HOT" letters ──
  {
    id: 'letter-T-1',
    src: '/images/collage/letter-T.png',
    alt: 'letter T 1',
    anchor: 'right',
    right: 312,
    top: 605,
    width: 46,
    rotation: -4,
    zIndex: 6,
  },
  {
    id: 'letter-H-1',
    src: '/images/collage/letter-H.png',
    alt: 'letter H 1',
    anchor: 'right',
    right: 265,
    top: 602,
    width: 46,
    rotation: 2,
    zIndex: 6,
  },
  {
    id: 'letter-A',
    src: '/images/collage/letter-A.png',
    alt: 'letter A',
    anchor: 'right',
    right: 224,
    top: 610,
    width: 36,
    rotation: -1,
    zIndex: 6,
  },
  {
    id: 'letter-T-2',
    src: '/images/collage/letter-T.png',
    alt: 'letter T 2',
    anchor: 'right',
    right: 183,
    top: 613,
    width: 41,
    rotation: 3,
    zIndex: 6,
  },
  {
    id: 'letter-S',
    src: '/images/collage/letter-S.png',
    alt: 'letter S',
    anchor: 'right',
    right: 145,
    top: 618,
    width: 30,
    rotation: -8,
    zIndex: 6,
  },
  {
    id: 'letter-H-2',
    src: '/images/collage/letter-H.png',
    alt: 'letter H 2',
    anchor: 'right',
    right: 281,
    top: 660,
    width: 31,
    rotation: -1,
    zIndex: 6,
  },
  {
    id: 'letter-O',
    src: '/images/collage/letter-O.png',
    alt: 'letter O',
    anchor: 'right',
    right: 230,
    top: 658,
    width: 46,
    rotation: 3,
    zIndex: 6,
  },
  {
    id: 'letter-T-3',
    src: '/images/collage/letter-T.png',
    alt: 'letter T 3',
    anchor: 'right',
    right: 183,
    top: 659,
    width: 46,
    rotation: -8,
    zIndex: 6,
  },
  // ── Peonies ──
  {
    id: 'peony-back',
    src: '/images/collage/peony.png',
    alt: 'Pink peony flower with green leaves',
    anchor: 'right',
    right: 34,
    top: 577,
    width: 170,
    rotation: -5,
    zIndex: 5,
  },
  {
    id: 'peony-front',
    src: '/images/collage/peony.png',
    alt: 'Pink peony flower with green leaves',
    anchor: 'right',
    right: -17,
    top: 610,
    width: 140,
    rotation: 31,
    zIndex: 6,
  },
];
